### PR TITLE
rename neovim import to pynvim

### PR DESCRIPTION
**Pull request by mcchrish**
See also https://github.com/roxma/nvim-yarp/pull/26

### CODE REVIEW

**Comment by mcchrish** [comment]
Somehow doing `pip3 install neovim` doesn't solve the problem. The packaged is renamed to `pynvim` already.

**Comment by clason** [comment]
No, you need `pip3 uninstall neovim && pip3 install pynvim` (upgrading doesn't work in all cases).

**Comment by mcchrish** [comment]
@clason tried that but doesn't work.

Running the command
```
❯ pip3 uninstall neovim && pip3 install pynvim
Skipping neovim as it is not installed.
Requirement already satisfied: pynvim in /usr/local/lib/python3.7/site-packages (0.3.1)
Requirement already satisfied: greenlet in /usr/local/lib/python3.7/site-packages (from pynvim) (0.4.15)
Requirement already satisfied: msgpack>=0.5.0 in /usr/local/lib/python3.7/site-packages (from pynvim) (0.5.6)
```

And the output of `:messages`:

```
[ncm2_core@yarp] Traceback (most recent call last):
[ncm2_core@yarp]   File "/Users/mcchris/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py", line 1, in <module>
[ncm2_core@yarp]     from neovim import attach, setup_logging
[ncm2_core@yarp] ModuleNotFoundError: No module named 'neovim'
[ncm2_core@yarp] Job is dead. cmd=['/usr/local/bin/python3', '-u', '/Users/mcchris/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/var/folders/fb/nctk069d4rz
83p4b87b4rx_w0000gp/T/nvim9l77HQ/0', 2, 'ncm2_core']
```

My neovim version:
```
NVIM v0.3.2-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20181120-3218-35oc8h/build/config -I/tmp/neovim-20181120-3218-35oc8h/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20181120-3218-35oc8h/build/src/nvim/auto -I/tmp/neovim-20181120-3218-35oc8h/build/include
Compiled by mcchris@mc-mba.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-3e87f5c/share/nvim"

Run :checkhealth for more info
```

Tried installing stable neovim and still the same.

And finally having both `neovim` and `pynvim` doesn't work too. I've tried hacking around and symlink `neovim` from `pynvim` inside the `/usr/local/lib/python3.7/site-packages` and it works.

**Comment by clason** [comment]
I've you've already upgraded `neovim` to `pynvim`, you need to uninstall that too: `pip3 uninstall neovim pynvim` before reinstalling `pynvim`. (Also, your first output doesn't look like it actually uninstalled `neovim` -- better try uninstalling and reinstalling as separate commands.)

**Comment by mcchrish** [comment]
@clason got it, it works now. Thanks!

I think the PR should still go through just to keep up with the latest change in neovim.

**Pull request closed without merging**
