### PR TITLE
Fix built-in LSP

### PR DESCRIPTION
**Pull request by Anexen**
Fix https://github.com/ncm2/ncm2/issues/180 caused by https://github.com/neovim/neovim/pull/11895.

### CODE REVIEW

**Comment by megalithic** [comment]
@roxma this fixes some bugs

**Comment by joshbode** [comment]
This has fixed #180 for me, also :)

**Comment by roxma** [comment]
Does `context.base` work for the issue? I would prefer to use `context.base`

**Comment by Anexen** [comment]
@roxma, yes, `context.base` works. Thanks.

**Pull request merged**
